sudo: required
services:
  - docker

before_install:
  - docker build -t test-runner -f Dockerfile.dev .

script:
  - docker run -e CI=true test-runner npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-675683048575"
  bucket_path: "frontend"
  on:
    branch: master
